### Login
### pippin@tuckborough.shire
### frodo@hobbiton.shire
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{"username": "pippin@tuckborough.shire", "password": "password"}
> {% client.global.set("authorized", response.body.token); %}

### get all notes for current user:
GET http://localhost:8080/api/notes
Authorization: Bearer {{ authorized }}

### add note:
POST http://localhost:8080/api/notes
Content-Type: application/json
Authorization: Bearer {{ authorized }}

{"title": "Note number Two", "body": "We are two steps from hell!"}

### First find a Note with /api/users/items and use the id here
### Post a comment:
POST http://localhost:8080/api/notes/3e6cf2a8-8c36-41eb-ae70-7c9e8a314ef1/comments
Content-Type: application/json
Authorization: Bearer {{ authorized }}

{"comment": "correct comment", "stars":  2}

### add tag to note
POST http://localhost:8080/api/notes/5442d394-7272-4910-9b81-4ba1a880aab8/tag/personal
Authorization: Bearer {{ authorized }}

### timeline
GET http://localhost:8080/api/users/timeline
Authorization: Bearer {{ authorized }}
