### Create Frodo:
POST https://server.vorhauer.nl/api/auth/register
Content-Type: application/json
Accept: application/json

{
  "name": "Frodo",
  "email": "frodo@hobbiton.shire",
  "password": "password"
}


### Create Bilbo:
POST https://server.vorhauer.nl/api/auth/register
Content-Type: application/json
Accept: application/json

{
  "name": "Bilbo",
  "email": "bilbo@hobbiton.shire",
  "password": "password"
}


### Create Pippin:
POST https://server.vorhauer.nl/api/auth/register
Content-Type: application/json
Accept: application/json

{
  "name": "Pippin",
  "email": "pippin@tuckborough.shire",
  "password": "password"
}

### Login Pippin
POST https://server.vorhauer.nl/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "pippin@tuckborough.shire",
  "password": "password"
}

> {% client.global.set("authorized", response.body.token); %}

### Get all users:
GET https://server.vorhauer.nl/api/users
Authorization: Bearer {{ authorized }}


### GET logged in user information:
GET https://server.vorhauer.nl/api/users/me
Authorization: Bearer {{ authorized }}


### get item(s):
GET https://server.vorhauer.nl/api/users/items
Authorization: Bearer {{ authorized }}


### get note(s):
GET https://server.vorhauer.nl/api/notes
Authorization: Bearer {{ authorized }}
Accept: application/json



### get notes for a user:
# id: be93fc71-7bf7-4cab-8161-8332e3f8bc42
GET https://server.vorhauer.nl/api/users/23dd3904-173b-42f3-9baf-6599c1aea881/notes
Authorization: Bearer {{ authorized }}


### add follower:
POST https://server.vorhauer.nl/api/users/follow/49899834-6467-4355-b3c2-e08f34d8b6a3
Authorization: Bearer {{ authorized }}


### get list of followers:
GET https://server.vorhauer.nl/api/users/followers
Authorization: Bearer {{ authorized }}


### get timeline:
GET https://server.vorhauer.nl/api/users/timeline
Authorization: Bearer {{ authorized }}


### create note:
POST https://server.vorhauer.nl/api/notes
Authorization: Bearer {{ authorized }}
Content-Type: application/json

{
  "title": "<h1>Titel</h1>",
  "body" : "Encode for HTML zou nu moeten zorgen dat \", &<javascript>alert('hello');</javascript> veilig worden"
}



### Retreive note with id be93fc71-7bf7-4cab-8161-8332e3f8bc42
GET https://server.vorhauer.nl/api/notes/24c8fe05-4397-41e2-8dd6-eb0d0c8ccc95
Authorization: Bearer {{ authorized }}
Accept: application/json
