version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      SERVER_SSL_KEY-STORE-PASSWORD: geheim-password-1
    depends_on:
      - postgres_db
  postgres_db:
    image: "postgres:13.2"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: noviaal
      POSTGRES_PASSWORD: d75xZC7kuxYdDFGH2EZJnEG
