= Noviaal - Novi Sociaal

|======
| Instelling    | NOVI HBO Software Development
| Leerlijn      | BackEnd
| Document      | Functioneel en Technisch Ontwerp voor de Eindopdracht
| Docent        | Nick Stuivenberg
| Datum         | 20 november 2020
| Auteur        | Jurjen Vorhauer
| Studentnummer | 800009793
| GitHub        | https://github.com/jvorhauer/noviaal
| *Noviaal*     | Een Twiiter-achtig platform, een samentrekking van NOVI en Sociaal
|======

<<<

:numbered:
== Inleiding

Dit is de REST applicatie die de eindopdracht voor NOVI HBO Software Development, module Backend 2019/2020 implementeert.

Een _platform_ om:

* notities en media op te slaan,
* om die notities te kunnen vinden, lezen en taggen.
* om andere gebruikers te volgen
* om direct geïnformeerd te worden over nieuwe notities van gevolgde gebruikers.

De doelgroep is *iedereen* op het internet.

== Documentatie

De documentatie is verdeeld in 4 delen:

. Functioneel Ontwerp (FO) in `documentatie/FO/noviaal-functioneel-ontwerp.pdf` met een diagram van alle geimplementeerde Use Cases en van iedere Use Case in dat diagram een beschrijving.
. Technische Ontwerp (TO) in `documentatie/TO/noviaal-technisch-ontwerp.pdf`
. Handleiding met o.a. Installatie instructies in `documentatie/handleiding.pdf`,
. Verantwoording met uitleg waar en hoe welke voorwaarden uit de Eindopdracht beschrijving zijn geimplementeerd in `documentatie/verantwoording.pdf`.
