@startuml class-diagram

title Noviaal Class Diagram

Note -- User

class User {
  - UUID     id
  - String   email
  - String   password
  - String   name
  - Boolean  enabled
  - Date     born
  - Role     role
  - DateTime since
}

enum Role {
  USER
  ADMIN
  REPORTER
}

User -- Role

abstract class BaseItem {
  - UUID id
  - DateTime created
  - DateTime updated
}

together {
  class Note extends BaseItem {
    - String title
    - String body
  }

  class Foto extends BaseItem {
    - Blob foto
  }

  class Video extends BaseItem {
    - Blob video
    - Int length
  }

  class Bookmark extends BaseItem {
    - URL url
    - String remark
  }
}

class Reminder {
  - DateTime when
  - DateTime created
  - String reason
}
BaseItem -- Reminder
Reminder -- User

class Like {
  - DateTime created
  - String reason
}
BaseItem -- Like
Like -- User

class Follow {
  - DateTime since
  - DateTime created
  - String   reason
}
User -- Follow
Follow -- User

class Tag {
  - DateTime created
  - String name
}
BaseItem -- Tag

@enduml
