@startuml

title Sequence Diagram - Nieuwe Notitie

actor User
actor Volger

User -> NotesController: post een note
NotesController -> NotesService: nieuwe note
NotesService -> NotesRepository: sla note op in db
NotesRepository -> Database: sla note op
Database --> NotesRepository: resultaat
NotesRepository --> NotesService: resultaat
NotesService -> TimeLineService: informeer volgers
TimeLineService -> Volger: nieuwe note
NotesService --> NotesController: resultaat
NotesController --> User: resultaat

@enduml
