@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v2.0.1/C4_Component.puml

LAYOUT_TOP_DOWN()
LAYOUT_WITH_LEGEND()

title Componenten diagram voor Noviaal

Person(person, "User")
Person(admin, "Administrator")
Person(reader, "Anonymous")

Container_Boundary(noviaal, "Noviaal Applicatie") {
  Component(authc, "AuthController", "Spring Security", "Verzorgt veilige login en registratie")
  Component(usersc, "UserController", "Spring MVC", "Levert registratie, vergeet-mij en blokkeer mogelijkheid")
  Component(notesc, "NoteController", "Spring MVC", "Maak nieuwe notities of update bestaande")
  Component(mediac, "MediaController", "Spring MVC", "Upload nieuwe media of download bestaande")
  Component(tagsc, "TagController", "Spring MVC", "Maak nieuwe tags of toon alle Notes bij een tag")

  Component(auths, "AuthService", "Soring/Java", "CRUD")
  Component(userss, "UserService", "Spring/Java", "CRUD")
  Component(notess, "NoteService", "Spring/Java", "CRUD")
  Component(medias, "MediaService", "Spring/Java", "CRUD")
  Component(tags, "TagService", "Spring/Java", "CRUD")

  Rel(authc, auths, "gebruikt")
  Rel(usersc, userss, "gebruikt")
  Rel(notesc, notess, "gebruikt")
  Rel(mediac, medias, "gebruikt")
  Rel(tagsc, tags, "gebruikt")
}

ComponentDb(db, "Database", "PostgreSQL", "Langdurige gegevens opslag")

Rel(notess, db, "JDBC")
Rel(userss, db, "JDBC")
Rel(tags, db, "JDBC")
Rel(medias, db, "JDBC")
Rel(auths, db, "JDBC")

Rel(person, authc, "https")
Rel(person, usersc, "https")
Rel(person, notesc, "https")
Rel(person, tagsc, "https")
Rel(person, mediac, "https")
Rel(admin, usersc, "https")
Rel(reader, authc, "https")

@enduml
