### Login Pippin
POST https://sheltered-gorge-50410.herokuapp.com/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "pippin@tuckborough.shire",
  "password": "password"
}

> {% client.global.set("authorized", response.body.token); %}


### get note(s):
GET https://sheltered-gorge-50410.herokuapp.com/api/notes
Authorization: Bearer {{ authorized }}
Accept: application/json


### POST a comment to an existing Note
# Pippin's ID: 1df84df2-add5-4b25-8b5f-4ddc587ba0f6
# Note ID: be93fc71-7bf7-4cab-8161-8332e3f8bc42 (eerste note, oorspronkelijke titel is "Test"
POST https://sheltered-gorge-50410.herokuapp.com/api/notes/be93fc71-7bf7-4cab-8161-8332e3f8bc42/comments
Authorization: Bearer {{ authorized }}
Accept: application/json
Content-Type: application/json

{
  "comment": "Dit is commentaar",
  "stars": 5
}

### get current users' note(s):
GET https://sheltered-gorge-50410.herokuapp.com/api/notes
Authorization: Bearer {{ authorized }}
Accept: application/json
