@startuml

title Like een Note (NC2 en IC4)

actor Gebruiker

Gebruiker --> NotitiesController: vraag Note met id
NotitiesController --> NotesService: zoek Note op id
NotesService --> database: query notes tabel op id
database --> NotesService: Note (0 of 1)
NotesService --> NotitiesController: Note (0 of 1)
NotitiesController --> Gebruiker: Note of 404

Gebruiker --> NotitiesController: Like Note
NotitiesController --> LikesService: Like Note met id
LikesService --> database: koppel gebruiker aan Note met Like
database --> LikesService: resultaat
LikesService --> NotitiesController: resultaat
NotitiesController --> Gebruiker: resultaat (200 of 400)

@enduml
