@startuml

Note -- Person

class Person {
  UUID     id
  String   email
  String   password
  Boolean  enabled
  Boolean  expired
  Date     born
  Role     role
  DateTime since
}

enum Role {
  USER
  ADMIN
}

Person -- Role

class Note {
  String     title
  String     body
  Visibility visibility
  DateTime   created
}

enum Visibility {
  PRIVATE
  FOLLOWERS
  PUBLIC
}

Note -- Visibility

Note -- Reminder
Reminder -- Person

class Reminder {
  DateTime when
  DateTime created
  String reason
}

Note -- Like
Like -- Person

class Like {
  DateTime created
  String reason
}

Person -- Follow
Follow -- Person

class Follow {
  Date     since
  DateTime created
  String   reason
}

Note "1" o- "0..*" Comment
Comment "1" o-- "0..*" Comment

class Comment {
  DateTime created
  String title
  String body
}

Note "0..*" -- "0..*" Tag

class Tag {
  DateTime created
  String name
}

@enduml
