CREATE TABLE IF NOT EXISTS notes
(
    id      UUID PRIMARY KEY,
    created TIMESTAMP WITH TIME ZONE,
    title   VARCHAR(255) NOT NULL,
    body    TEXT
);

CREATE TABLE IF NOT EXISTS users
(
    email   VARCHAR(1024) PRIMARY KEY,
    password VARCHAR(255) NOT NULL,
    nickname VARCHAR(255),
    created  TIMESTAMP WITH TIME ZONE
);
